// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	error_v1 "github.com/patyukin/mbs-pkg/pkg/proto/error_v1"

	mock "github.com/stretchr/testify/mock"

	model "github.com/patyukin/mbs-api-gateway/internal/model"
)

// LoggerUseCase is an autogenerated mock type for the LoggerUseCase type
type LoggerUseCase struct {
	mock.Mock
}

// GetLogReportV1UseCase provides a mock function with given fields: ctx, in
func (_m *LoggerUseCase) GetLogReportV1UseCase(ctx context.Context, in model.GetLogReportV1Request) (model.GetLogReportV1Response, *error_v1.ErrorResponse) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetLogReportV1UseCase")
	}

	var r0 model.GetLogReportV1Response
	var r1 *error_v1.ErrorResponse
	if rf, ok := ret.Get(0).(func(context.Context, model.GetLogReportV1Request) (model.GetLogReportV1Response, *error_v1.ErrorResponse)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetLogReportV1Request) model.GetLogReportV1Response); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(model.GetLogReportV1Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetLogReportV1Request) *error_v1.ErrorResponse); ok {
		r1 = rf(ctx, in)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*error_v1.ErrorResponse)
		}
	}

	return r0, r1
}

// NewLoggerUseCase creates a new instance of LoggerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerUseCase {
	mock := &LoggerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
