min_log_level: "debug"
server:
  port: 5001
  read_timeout: 10
  write_timeout: 5
telegram:
  token: "token"
jwt_secret: "jwt_secret"
postgresql:
  host: "db"
  port: 5432
  user: "user"
  password: "1234"
  name: "auth"
redis:
  host: "redis"
  port: 6379
