services:
  mbs-api-gateway:
    build:
      dockerfile: local.Dockerfile
    container_name: mbs-api-gateway-container
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201" # Адрес и порт Graylog
        tag: "mbs-api-gateway"              # Тег логов
    volumes:
      - .:/app
    restart: always
    ports:
      - "5002:5002"
    networks:
      - mbs

networks:
  mbs:
    name: mbs
    external: true
