services:
  mbs-api-gateway:
    build:
      dockerfile: local.Dockerfile
    container_name: mbs-api-gateway-container
    volumes:
      - .:/app
    restart: always
    ports:
      - "5002:5002"
    networks:
      - mbs

networks:
  mbs:
    name: mbs
    external: true
